const zones = [
  "NATIONAL",
  "DKI_JAKARTA",
  "JAWA_BARAT",
  "JAWA_TIMUR",
  "JAWA_TENGAH",
  "SULAWESI_SELATAN",
  "BANTEN",
  "NUSA_TENGGARA_BARAT",
  "BALI",
  "PAPUA",
  "KALIMANTAN_SELATAN",
  "SUMATERA_BARAT",
  "SUMATERA_SELATAN",
  "KALIMANTAN_TENGAH",
  "KALIMANTAN_TIMUR",
  "SUMATERA_UTARA",
  "DAERAH_ISTIMEWA_YOGYAKARTA",
  "KALIMANTAN_UTARA",
  "KEPULAUAN_RIAU",
  "KALIMANTAN_BARAT",
  "SULAWESI_TENGGARA",
  "LAMPUNG",
  "SULAWESI_UTARA",
  "SULAWESI_TENGAH",
  "RIAU",
  "PAPUA_BARAT",
  "SULAWESI_BARAT",
  "JAMBI",
  "MALUKU_UTARA",
  "MALUKU",
  "GORONTALO",
  "KEPULAUAN_BANGKA_BELITUNG",
  "ACEH",
  "BENGKULU",
  "NUSA_TENGGARA_TIMUR",
];
const defaultZones = [
  "NATIONAL",

  "RIAU",
  "KALIMANTAN_BARAT",
  "DAERAH_ISTIMEWA_YOGYAKARTA",
  "KEPULAUAN_RIAU",
  "BENGKULU",
  "JAWA_TIMUR",
  "SULAWESI_UTARA",
  "LAMPUNG",
  "BANTEN",
  "PAPUA",
  "KALIMANTAN_SELATAN",
  "DKI_JAKARTA",
  "MALUKU_UTARA",
  "MALUKU",

  "SULAWESI_SELATAN",
  "JAWA_TENGAH",
  "JAWA_BARAT",
  "SUMATERA_SELATAN",
];
const defaultPeriods = 3;
const defaultHiddenDatasets = [true, true, true, true, false, false, false, false, true, true, true, true];

const cases = ["confirmed", "recover", "death", "active"];

export { zones, defaultZones, defaultPeriods, defaultHiddenDatasets, cases };
